### ISSUE TITLE
Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by abdullah249** [claudiobosetti/TikTokTool#2]
hi Claudio,
I got into an issue and it says "Cannot run the event loop while another loop is running". And I am having issues to run the commands can you guide me.

**Comment by claudiobosetti** [comment]
Hey, sorry for my late reply. I think the problem is only that there is already an instance of python running, try closing the process and restarting the script. If that doesn't work, please send me a full log. Good luck ;)

**Comment by abdullah249** [comment]
OK thank you
